### ISSUE TITLE
Cannot build on openSUSE 15.2

### ISSUE THREAD

**Issue by arjantenhoopen** [keur/prettyeq#2]
I am unable to build it, here's the output:

arjan@arjanpc:/tenhoopen/git/prettyeq/build> qmake CONFIG+=release ..
arjan@arjanpc:/tenhoopen/git/prettyeq/build> make -j4
cd equalizer/ && /usr/bin/qmake /tenhoopen/git/prettyeq/equalizer/equalizer.pro CONFIG+=release -o Makefile
cd gui/ && /usr/bin/qmake /tenhoopen/git/prettyeq/gui/gui.pro CONFIG+=release -o Makefile
**/tenhoopen/git/prettyeq/equalizer/equalizer.pro:10: Parse Error ('pretty.h')
Error processing project file: /tenhoopen/git/prettyeq/equalizer/equalizer.pro**
make: *** [Makefile:33: equalizer/Makefile] Fout 3
make: *** Wachten op onvoltooide taken...
arjan@arjanpc:/tenhoopen/git/prettyeq/build> make -j4
cd equalizer/ && /usr/bin/qmake /tenhoopen/git/prettyeq/equalizer/equalizer.pro CONFIG+=release -o Makefile
cd equalizer/ && make -f Makefile 
make[1]: Map '/tenhoopen/git/prettyeq/build/equalizer' wordt binnengegaan
gcc -c -pipe -ffast-math -fopenmp -O2 -fPIC -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../equalizer -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I../../equalizer -I. -o arena.o ../../equalizer/arena.c
gcc -c -pipe -ffast-math -fopenmp -O2 -fPIC -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../equalizer -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I../../equalizer -I. -o fft.o ../../equalizer/fft.c
gcc -c -pipe -ffast-math -fopenmp -O2 -fPIC -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../equalizer -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I../../equalizer -I. -o pretty.o ../../equalizer/pretty.c
**../../equalizer/pretty.c:6:10: fatal error: pulse/pulseaudio.h: Bestand of map bestaat niet
 #include <pulse/pulseaudio.h>
          ^~~~~~~~~~~~~~~~~~~~**
compilation terminated.
make[1]: *** [Makefile:223: pretty.o] Fout 1
make[1]: *** Wachten op onvoltooide taken...
make[1]: Map '/tenhoopen/git/prettyeq/build/equalizer' wordt verlaten
make: *** [Makefile:40: sub-equalizer-make_default-ordered] Fout 2
arjan@arjanpc:/tenhoopen/git/prettyeq/build>

I solved the Parse error, I removed the last line. However where can I get the headerfile pulse/pulseaudio.h

Any help is appreciated.
Cheers,
Arjan

**Comment by kkuehlz** [comment]
Can you try with the pulseaudio-devel package?

**Comment by arjantenhoopen** [comment]
Making progress, added libpulse-devel  libqt5-qtbase-devel packages but now I get stuck at:
```

g++ -c -pipe -O2 -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../gui -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../equalizer -I. -I. -I../../gui -I. -o prettygraphicsscene.o ../../gui/prettygraphicsscene.cpp
../../gui/gui.cpp:27:10: fatal error: QtMath: Bestand of map bestaat niet
 #include <QtMath>
          ^~~~~~~~
```
compilation terminated.

AND

```
../../gui/frequencytick.cpp:11:31: error: ‘systemFont’ is not a member of ‘QFontDatabase’
     QFont ff = QFontDatabase::systemFont(QFontDatabase::FixedFont);
                               ^~~~~~~~~~
../../gui/frequencytick.cpp:11:57: error: ‘**FixedFont**’ is not a member of ‘QFontDatabase’
     QFont ff = QFontDatabase::systemFont(QFontDatabase::FixedFont);
                                                         ^~~~~~~~~
../../gui/frequencytick.cpp:25:25: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
         int offset = fm.horizontalAdvance(QLatin1Char('K')) * 4;
                         ^~~~~~~~~~~~~~~~~
../../gui/frequencytick.cpp:30:25: error: ‘class **QFontMetrics**’ has no member named ‘horizontalAdvance’
         int offset = fm.horizontalAdvance(QLatin1Char('K')) * toQString().length() + 7;
                         ^~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:317: frequencytick.o] Fout 1
```
I am at Qt 5.12.7 (libQt5Core-devel-5.12.7-lp152.3.16.1.x86_64)

TIA,
Arjan

**Comment by kkuehlz** [comment]
@arjantenhoopen Odd because I believe the `horizontalAdvance` methods were included in 5.11. Can you try updating to Qt 5.15 and see if you can compile?

**Comment by arjantenhoopen** [comment]
I am now at 5.15:

arjan@arjanpc:/tenhoopen/git/prettyeq/build> rpm -qa|grep libQt5Core
libQt5Core5-5.15.2-lp152.7.1.x86_64
libQt5Core-devel-5.15.2-lp152.7.1.x86_64
libQt5Core5-debuginfo-5.15.2-lp152.7.1.x86_64
arjan@arjanpc:/tenhoopen/git/prettyeq/build>

Full build output:

arjan@arjanpc:/tenhoopen/git/prettyeq> mkdir build
arjan@arjanpc:/tenhoopen/git/prettyeq> cd build
arjan@arjanpc:/tenhoopen/git/prettyeq/build> qmake CONFIG+=release ..
arjan@arjanpc:/tenhoopen/git/prettyeq/build> ls -l
totaal 12
-rw-r--r-- 1 arjan users 8495 22 apr 11:13 Makefile
arjan@arjanpc:/tenhoopen/git/prettyeq/build> make -j4
cd equalizer/ && /usr/bin/qmake /tenhoopen/git/prettyeq/equalizer/equalizer.pro CONFIG+=release -o Makefile
cd gui/ && /usr/bin/qmake /tenhoopen/git/prettyeq/gui/gui.pro CONFIG+=release -o Makefile
cd equalizer/ && make -f Makefile 
make[1]: Map '/tenhoopen/git/prettyeq/build/equalizer' wordt binnengegaan
gcc -c -pipe -ffast-math -fopenmp -O2 -fPIC -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../equalizer -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I../../equalizer -I. -o arena.o ../../equalizer/arena.c
gcc -c -pipe -ffast-math -fopenmp -O2 -fPIC -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../equalizer -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I../../equalizer -I. -o fft.o ../../equalizer/fft.c
gcc -c -pipe -ffast-math -fopenmp -O2 -fPIC -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../equalizer -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I../../equalizer -I. -o pretty.o ../../equalizer/pretty.c
rm -f libequalizer.a
ar cqs libequalizer.a arena.o fft.o pretty.o
make[1]: Map '/tenhoopen/git/prettyeq/build/equalizer' wordt verlaten
cd gui/ && make -f Makefile 
make[1]: Map '/tenhoopen/git/prettyeq/build/gui' wordt binnengegaan
/usr/bin/uic ../../gui/gui.ui -o ui_gui.h
g++ -c -pipe -O2 -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../gui -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../equalizer -I. -I. -I../../gui -I. -o collisionmanager.o ../../gui/collisionmanager.cpp
g++ -c -pipe -O2 -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../gui -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../equalizer -I. -I. -I../../gui -I. -o curvepoint.o ../../gui/curvepoint.cpp
g++ -c -pipe -O2 -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../gui -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../equalizer -I. -I. -I../../gui -I. -o eqhoverer.o ../../gui/eqhoverer.cpp
g++ -c -pipe -O2 -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../gui -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../equalizer -I. -I. -I../../gui -I. -o filtercurve.o ../../gui/filtercurve.cpp
In file included from ../../gui/filtercurve.h:4:0,
                 from ../../gui/filtercurve.cpp:1:
../../gui/prettyshim.h: In member function ‘void PrettyShim::init()’:
../../gui/prettyshim.h:35:13: warning: unused variable ‘r’ [-Wunused-variable]
         int r = pretty_init();
             ^
../../gui/prettyshim.h: In member function ‘void PrettyShim::new_filter(PrettyFilter**)’:
../../gui/prettyshim.h:48:13: warning: unused variable ‘r’ [-Wunused-variable]
         int r = pretty_new_filter(filter);
             ^
In file included from ../../gui/filtercurve.h:4:0,
                 from ../../gui/curvepoint.h:4,
                 from ../../gui/eqhoverer.h:4,
                 from ../../gui/eqhoverer.cpp:2:
../../gui/prettyshim.h: In member function ‘void PrettyShim::init()’:
../../gui/prettyshim.h:35:13: warning: unused variable ‘r’ [-Wunused-variable]
         int r = pretty_init();
             ^
../../gui/prettyshim.h: In member function ‘void PrettyShim::new_filter(PrettyFilter**)’:
../../gui/prettyshim.h:48:13: warning: unused variable ‘r’ [-Wunused-variable]
         int r = pretty_new_filter(filter);
             ^
In file included from ../../gui/filtercurve.h:4:0,
                 from ../../gui/curvepoint.h:4,
                 from ../../gui/eqhoverer.h:4,
                 from ../../gui/collisionmanager.cpp:2:
../../gui/prettyshim.h: In member function ‘void PrettyShim::init()’:
../../gui/prettyshim.h:35:13: warning: unused variable ‘r’ [-Wunused-variable]
         int r = pretty_init();
             ^
../../gui/prettyshim.h: In member function ‘void PrettyShim::new_filter(PrettyFilter**)’:
../../gui/prettyshim.h:48:13: warning: unused variable ‘r’ [-Wunused-variable]
         int r = pretty_new_filter(filter);
             ^
In file included from ../../gui/filtercurve.h:4:0,
                 from ../../gui/curvepoint.h:4,
                 from ../../gui/curvepoint.cpp:1:
../../gui/prettyshim.h: In member function ‘void PrettyShim::init()’:
../../gui/prettyshim.h:35:13: warning: unused variable ‘r’ [-Wunused-variable]
         int r = pretty_init();
             ^
../../gui/prettyshim.h: In member function ‘void PrettyShim::new_filter(PrettyFilter**)’:
../../gui/prettyshim.h:48:13: warning: unused variable ‘r’ [-Wunused-variable]
         int r = pretty_new_filter(filter);
             ^
g++ -c -pipe -O2 -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../gui -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../equalizer -I. -I. -I../../gui -I. -o frequencytick.o ../../gui/frequencytick.cpp
g++ -c -pipe -O2 -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../gui -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../equalizer -I. -I. -I../../gui -I. -o frequencytickbuilder.o ../../gui/frequencytickbuilder.cpp
g++ -c -pipe -O2 -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../gui -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../equalizer -I. -I. -I../../gui -I. -o gui.o ../../gui/gui.cpp
g++ -c -pipe -O2 -Wall -W -Wno-unused-parameter -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I../../gui -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../../equalizer -I. -I. -I../../gui -I. -o highshelfcurve.o ../../gui/highshelfcurve.cpp
../../gui/gui.cpp:27:10: fatal error: QtMath: Bestand of map bestaat niet
 #include <QtMath>
          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:341: gui.o] Fout 1
make[1]: *** Wachten op onvoltooide taken...
../../gui/frequencytick.cpp: In constructor ‘FrequencyTick::FrequencyTick(QGraphicsScene*, int, int, int, int)’:
../../gui/frequencytick.cpp:11:31: error: ‘systemFont’ is not a member of ‘QFontDatabase’
     QFont ff = QFontDatabase::systemFont(QFontDatabase::FixedFont);
                               ^~~~~~~~~~
../../gui/frequencytick.cpp:11:57: error: ‘FixedFont’ is not a member of ‘QFontDatabase’
     QFont ff = QFontDatabase::systemFont(QFontDatabase::FixedFont);
                                                         ^~~~~~~~~
../../gui/frequencytick.cpp:25:25: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
         int offset = fm.horizontalAdvance(QLatin1Char('K')) * 4;
                         ^~~~~~~~~~~~~~~~~
../../gui/frequencytick.cpp:30:25: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
         int offset = fm.horizontalAdvance(QLatin1Char('K')) * toQString().length() + 7;
                         ^~~~~~~~~~~~~~~~~
In file included from ../../gui/filtercurve.h:4:0,
                 from ../../gui/curvepoint.h:4,
                 from ../../gui/shelfcurve.h:4,
                 from ../../gui/highshelfcurve.h:4,
                 from ../../gui/highshelfcurve.cpp:1:
../../gui/prettyshim.h: In member function ‘void PrettyShim::init()’:
../../gui/prettyshim.h:35:13: warning: unused variable ‘r’ [-Wunused-variable]
         int r = pretty_init();
             ^
../../gui/prettyshim.h: In member function ‘void PrettyShim::new_filter(PrettyFilter**)’:
../../gui/prettyshim.h:48:13: warning: unused variable ‘r’ [-Wunused-variable]
         int r = pretty_new_filter(filter);
             ^
make[1]: *** [Makefile:317: frequencytick.o] Fout 1
make[1]: Map '/tenhoopen/git/prettyeq/build/gui' wordt verlaten
make: *** [Makefile:76: sub-gui-make_default-ordered] Fout 2
arjan@arjanpc:/tenhoopen/git/prettyeq/build>

Any help to get it working is appreciated!

**Comment by kkuehlz** [comment]
@arjantenhoopen Ah I sees I think you need to build with the qmake-qt5 executable. Your qmake is for qt4.

**Comment by arjantenhoopen** [comment]
@keur Did the trick :)

Maybe mention it in the README :) and that Qt>=5.15

Thanks for support
Cheers,
Arjan

FYI: one message during compilation:
g++ -c -pipe -O2 -std=gnu++11 -Wall -Wextra -Wno-unused-parameter -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../gui -I. -I../../equalizer -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o spectrumanalyzer.o ../../gui/spectrumanalyzer.cpp
../../gui/runguard.cpp: In constructor ‘RunGuard::RunGuard()’:
../../gui/runguard.cpp:15:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wstringop-truncation"
                                ^~~~~~~~~~~~~~~~~~~~~~~
